version: "3"

services:
  promtail:
    image: grafana/promtail:2.5.0
    restart: always
    volumes:
      - /var/log:/var/log
      - ./config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml

